Lint/AmbiguousOperator:
  Enabled: true
Lint/AmbiguousRegexpLiteral:
  Enabled: true
Lint/AssignmentInCondition:
  Enabled: true
Lint/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: 'start_of_block'
Lint/CircularArgumentReference:
  Enabled: true
Lint/DefEndAlignment:
  EnforcedStyleAlignWith: 'def'
Lint/InheritException:
  EnforcedStyle: 'standard_error'
